const routes = {
    home: '/',
    billpayments: '/billpayments',
    blog: '/blog',
    businesstravelexpenses: '/businesstravelexpenses',
    customers: '/customers',
    ebooks: '/ebooks',
    integrations: '/integrations',
    invoiceManagement: '/invoicemanagement',
    login: '/login',
    podcast: '/podcast',
    pricing: '/pricing',
    productexpensemanagement: '/productexpensemanagement',
    productvisacards: '/productvisacards',
    subscriptions: '/subscriptions',
    demo: '/demo',
    ebookfreeplatform: '/ebookfreeplatform',
    help: '/help,',
    product: './product',
    download: '/download',
    whypayhawk: '/whypayhawk',
    webinars: '/webinars',
    security: '/security',
    usecase: '/usecase',
};

export default routes;
